// <auto-generated />
using Centoreal.Entities.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Centoreal.Entities.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20210803122748_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Centoreal.Entities.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "Professor Colony",
                            City = "Hyderabad",
                            Country = "India",
                            State = "Telangana"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "Kankarbagh",
                            City = "Patna",
                            Country = "India",
                            State = "Bihar"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "Saket Colony",
                            City = "Delhi",
                            Country = "India",
                            State = "Delhi"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "Dream Palace",
                            City = "Himachal",
                            Country = "India",
                            State = "Uttarakhand"
                        });
                });

            modelBuilder.Entity("Centoreal.Entities.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Name = "Amit Bhadra"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Name = "Suresh Roy"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            Name = "Kranti Raina"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            Name = "Angelina Singh"
                        });
                });

            modelBuilder.Entity("Centoreal.Entities.Models.Student", b =>
                {
                    b.HasOne("Centoreal.Entities.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
